// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using online_job_finder.DataBase.Models;

#nullable disable

namespace online_job_finder.DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250301143542_Add Skill,Location")]
    partial class AddSkillLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("online_job_finder.DataBase.Models.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LocationId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<int?>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("PK__company___3213E83F7BEECB56");

                    b.ToTable("company_profiles", (string)null);
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblJobCategory", b =>
                {
                    b.Property<Guid>("JobCategoryID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobCategeory_Id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCategoryID");

                    b.ToTable("Tbl_JobCategories", (string)null);
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblLocation", b =>
                {
                    b.Property<Guid>("LocationID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Location_ID");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Tbl_Locations", (string)null);
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role_Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_at");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Delete");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role_Name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Tbl_Role", (string)null);
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblSkill", b =>
                {
                    b.Property<Guid>("SkillID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Skill_Id");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Tbl_Skills", (string)null);
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("User_Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Delete");

                    b.Property<bool>("IsInformationCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Information_Completed");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Profile_Photo");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Role_Id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Version"));

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Tbl_Users_Role_Id");

                    b.ToTable("Tbl_Users", (string)null);
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblUser", b =>
                {
                    b.HasOne("online_job_finder.DataBase.Models.TblRole", "Role")
                        .WithMany("TblUsers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Tbl_Users_Tbl_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("online_job_finder.DataBase.Models.TblRole", b =>
                {
                    b.Navigation("TblUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
